

module.exports = {

    

  ADD_PATIENT: `INSERT INTO patient (
    PATIENT_ID, NAME, DATE_OF_BIRTH, GENDER, DISTRICT, ADDRESS, EMAIL, PHONE, USER_PASSWORD, DELETED, USER_TYPE,
    CREATED_DATE, LAST_LOGIN_DATE, INVALIED_LOGIN_COUNT, IS_ACTIVE
  ) 
  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `,
  GET_ALL_PATIENT: `SELECT * FROM patient`,
  GET_PATIENT_BY_ID: `SELECT * FROM patient WHERE PATIENT_ID=?`,
  GET_PATIENT_BY_EMAIL: `SELECT * FROM patient WHERE EMAIL=?`,
  GET_PATIENT_ID_BY_EMAIL: `SELECT PATIENT_ID FROM patient WHERE EMAIL =?`,
  UPDATE_PATIENT: `UPDATE patient set NAME=?, DATE_OF_BIRTH=?, GENDER=?,DISTRICT=?, ADDRESS=?, EMAIL=?,PHONE=?, USER_PASSWORD=?, DELETED=?,USER_TYPE=?, CREATED_USER=?, CREATED_DATE=?,LAST_LOGIN_DATE=?, INVALIED_LOGIN_COUNT=?, IS_ACTIVE=?,  where PATIENT_ID=?`,
  LOGIN_UPDATE: `UPDATE patient set LAST_LOGIN_DATE=?, IS_ACTIVE=? WHERE EMAIL =?`,
  INVALIED_LOGIN_COUNT_UPDATE: `UPDATE patient set INVALIED_LOGIN_COUNT = INVALIED_LOGIN_COUNT + 1 WHERE EMAIL =?`,
  LOGOUT: `UPDATE patient set INVALIED_LOGIN_COUNT=?, IS_ACTIVE=? WHERE EMAIL =?`,
  GET_LOGIN_STATUS: `SELECT IS_ACTIVE FROM patient WHERE EMAIL =?`,
  SOFT_DELETE_PATIENT: `UPDATE patient set DELETED=1 where PATIENT_ID=?`,
  DELETE_PATIENT: `DELETE FROM patient WHERE PATIENT_ID=?`,
  UPDATE_PATIENT_PASSWORD: `UPDATE patient set USER_PASSWORD=? where EMAIL=?`,


  ADD_OTP: `INSERT INTO otp(PATIENT_ID, OTP_NUMBER, OTP_VALIDITY_PERIOD) VALUES(?, ?, ?)`,
  DELETE_OTP: `DELETE FROM otp WHERE PATIENT_ID =?`,
  GET_OTP_BY_PATIENTID: `SELECT OTP_NUMBER FROM WHERE PATIENT_ID =?`,
  GET_ALL_OTP_RECODE_BY_EMAIL: `SELECT * FROM otp WHERE PATIENT_ID =?`
  
}